name: work_example
description: Demonstrates how to use the work package.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0

dependencies:
  json_annotation: ^4.9.0
  work:
    # When depending on this package from a real application you should use:
    #   work: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version. 
    path: ../

dev_dependencies:
  test: ^1.25.8

  build_runner: ^2.4.12
  json_serializable: ^6.8.0