name: work
description: Encapsulate http business interface protocol, provide limited extension functions, isolate the underlying implementation method of http (currently based on dio).

version: 0.5.4

homepage: https://github.com/cwkProject/work
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  dio: ^3.0.4
  mime: ^0.9.6+2
  http_parser: ^3.1.4
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.9.0