name: work
description: Encapsulate http business interface protocol, provide limited extension functions, isolate the underlying implementation method of http (currently based on dio).

version: 7.0.0

homepage: https://github.com/cwkProject/work

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.16.0
  dio: ^5.7.0
  mime: ^1.0.6
  http_parser: ^4.0.2
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^5.0.0