name: work
description: Encapsulate http business interface protocol, provide limited extension functions, isolate the underlying implementation method of http (currently based on dio).

version: 3.2.2

homepage: https://github.com/cwkProject/work

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  dio: ^4.0.6
  mime: ^1.0.0
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1