name: work
description: Encapsulate http business interface protocol, provide limited extension functions, isolate the underlying implementation method of http (currently based on dio), and closely integrate with the company's http specification to regulate the writing and use of team member interfaces.

version: 0.4.5

homepage: https://github.com/cwkProject/work
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  dio: ^3.0.4
  mime: ^0.9.6+2
  http_parser: ^3.1.4
  path: ^1.6.4