name: work
description: 封装http业务接口
version: 0.4.3
author: 超悟空 <cwk39251474@gmail.com>
homepage: https://github.com/cwkProject/work/tree/master/work
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  dio: ^3.0.4
  mime: ^0.9.6+2
  http_parser: ^3.1.4
  path: ^1.6.4

dev_dependencies: